# Generated by Django 4.1.3 on 2022-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'annually')], default='monthly', max_length=9)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
